<a href="https://colab.research.google.com/github/mssamoilenko/AI_HW1/blob/master/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [3]:
b = a[a % 2 == 0]
b

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію np.linspace

In [4]:
g = np.linspace(0, 0.9,10)
g

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [5]:
def gener_new_matrix(matrix):
    n = matrix.shape[0]
    new_matrix = np.zeros((n+2, n+2), dtype=matrix.dtype)
    new_matrix[1: n+1, 1: n+1] = matrix
    return new_matrix
matrix=np.array([[1,2],[3,4]])
gener_new_matrix(matrix)

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [9]:
n = gener_new_matrix(matrix)
n_float = n.astype('float32')

n_float.dtype
n_float

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 0., 0., 0.]], dtype=float32)

#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [11]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

In [12]:
x[x == var] = -1

In [13]:
x[x > var] = -1

In [14]:
x[x < var] = -1

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [16]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

In [21]:
X[np.isnan(X)] = -1
X

array([[ 1.,  2., -1.,  4.],
       [ 5., -1., -1.,  4.],
       [-1., 10., 11., -1.]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [32]:
arr = np.random.randint(1, 100,(4,6))
arr.reshape(3,8)

array([[47, 16, 95, 98, 84, 59, 60, 46],
       [66, 56, 80, 13, 54, 59, 34, 32],
       [28, 73, 94, 76, 34, 45, 98, 50]])

#Завдання 9
Створіть випадкову матрицю розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [36]:
arr = np.random.randint(1, 100,(3,4))
arr

x1 = arr[:, 0]
resx1 = np.mean(x1)

x2 = arr[:, 1]
resx2 = np.mean(x2)

x3 = arr[:, 2]
resx3 = np.mean(x3)

x4 = arr[:, 3]
resx4 = np.mean(x4)




#Завдання 10
Є матриця з ймовірностями того, що зображення(рядки) належить певному класу(стовпчики). Для кожного зображення(рядка) знайдіть індекс класу(стовпчика) з найбільшою ймовірністю

In [37]:
x = np.array([[0.2 , 0.3 , 0.23, 0.07, 0.03, 0.17],
              [0.15, 0.06, 0.21, 0.12, 0.24, 0.24],
              [0.1 , 0.21, 0.03, 0.07, 0.31, 0.28],
              [0.21, 0.24, 0.03, 0.18, 0.12, 0.21],
              [0.19, 0.25, 0.25, 0.06, 0.12, 0.12]])

max_indices = np.argmax(x, axis=1)
max_indices

array([1, 4, 4, 1, 1])

Пояснення: в першому рядку найбільша ймовірність -- 0.3 під індексом 1

в другому рядку -- 0.24 під індексом 4

в третьому рядку -- 0.31 під індексом 4

в четвертому рядку -- 0.24 під індексом 1

в п'ятому рядку -- 0.25 під індексом 1(там є ще одне 0.25, але ми беремо те що з меншим індексом)


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [38]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

In [42]:
mask = np.logical_and(X >= 3, X <= 6)

result = X[mask]
result

array([3, 4, 5, 6, 6, 5, 4, 3])

#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [43]:
matrix = np.random.randint(0, 10, size=(5, 6))
matrix

array([[0, 2, 4, 5, 3, 8],
       [7, 5, 6, 9, 9, 6],
       [5, 0, 5, 5, 8, 6],
       [1, 4, 1, 2, 3, 2],
       [7, 3, 6, 3, 3, 7]])

In [44]:
min_vals = matrix.min(axis=0)
max_vals = matrix.max(axis=0)

normalized_matrix = (matrix - min_vals) / (max_vals - min_vals)
normalized_matrix

array([[0.        , 0.4       , 0.6       , 0.42857143, 0.        ,
        1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.66666667],
       [0.71428571, 0.        , 0.8       , 0.42857143, 0.83333333,
        0.66666667],
       [0.14285714, 0.8       , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.6       , 1.        , 0.14285714, 0.        ,
        0.83333333]])